# 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors in PyTorch

### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [6]:
type(scalar)

torch.Tensor

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as Python int
# Converts element to scalar. Cannot be used on higher ndmim objects
scalar.item()

3

In [12]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [14]:
# Number of dimension (ndim) corresponds to number of square brackets
vector.ndim

1

In [22]:
# Slicing
vector[0:2]

tensor([1, 2])

In [27]:
# Matrix
# For simplicity use numpy to create a 3x3 array for torch.tensor to use
arr = np.arange(0,9).reshape(3,3)
matrix = torch.tensor(arr)
matrix

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [28]:
matrix.ndim

2

In [29]:
matrix[1]

tensor([3, 4, 5])

In [30]:
matrix[0:2]

tensor([[0, 1, 2],
        [3, 4, 5]])

In [31]:
matrix.shape

torch.Size([3, 3])

In [35]:
# Tensor
arr2 = np.arange(0,18).reshape(2,3,3)
tensor = torch.tensor(arr2)
tensor

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [36]:
tensor.shape

torch.Size([2, 3, 3])

In [37]:
tensor.ndim

3

In [6]:
test = torch.tensor([[[
        [[0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]]]])

test.shape

torch.Size([1, 1, 2, 3, 3])

### Random tensors

Why random tensors? 

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [12]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2720, 0.1451, 0.8149, 0.3579],
        [0.1437, 0.8165, 0.8511, 0.2947],
        [0.5623, 0.5871, 0.2964, 0.1497]])

In [13]:
random_tensor.ndim

2

In [14]:
random_tensor.shape

torch.Size([3, 4])

In [15]:
# Create a random tensor with similar shape to an image tensor 
random_image_size_tensor = torch.rand(size=(3, 224, 224)) # colour channels, height, width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [26]:
# Create a tensor of all zeros
zeroes = torch.zeros(size=(3,4))
zeroes

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [17]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
zeroes.dtype, ones.dtype

(torch.float32, torch.float32)

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.arange(), returns a 1-D tensor
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
torch.arange(start=0, end=101, step=2)

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100])

In [28]:
# Creating tensors like
# Often, when you’re performing operations on two or more tensors, they will need to be of the same shape - that is, having the same number of dimensions and the same number of cells in each dimension. For that, we have the torch.*_like() methods:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[-3.1353e+04,  3.2425e-41,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00]],

        [[ 1.0000e+00,  1.0000e+00,  1.0000e+00],
         [ 1.0000e+00,  1.0000e+00,  1.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[1.3593e-43, 1.5414e-43, 1.4433e-43],
         [1.4153e-43, 5.6052e-44, 1.6115e-43]],

        [[1.6255e-43, 1.3593e-43, 1.5975e-43],
         [1.6255e-43, 8.5479e-44, 6.7262e-44]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6539, 0.8049, 0.4488],
         [0.6111, 0.2388, 0.0135]],

        [[0.8345, 0.7398, 0.9308],
         [0.3962, 0.4738, 0.5468]]])


### Tensor datatypes

In [32]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float16 or float32)
                               device=None, # what device the tensor is on (default is cpu; cuda is gpu)
                               requires_grad=False # whether or not to track gradients with this tensors operations
                              )

float_32_tensor, float_32_tensor.dtype
# dtype is float32 even though dtype=None -> float32 is default

(tensor([3., 6., 9.]), torch.float32)

In [35]:
# Float 16 tensor: sacrifice some detail of how the numbers are represented <-> calculate faster and take up less space in memory as compared to float 32
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

The available datatypes in PyTorch are listed in https://pytorch.org/docs/stable/tensors.html

**Note**: Tensor datatypes is one of the 3 big errors encountered in PyTorch and deep learning:
1. Tensor is not right datatype
2. Tensor is not right shape
3. Tensor is not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [37]:
float_32_tensor*float_16_tensor # not all operations throw an error

tensor([ 9., 36., 81.])

In [39]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [40]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting attributes from tensors

1. Tensor is not right datatype - to get datatype from a tensor, can use `tensor.dtype`
2. Tensor is not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensor is not on the right device - to get device from a tensor, can use `tensor.device`

In [41]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.3111, 0.7698, 0.9164, 0.4658],
        [0.2432, 0.7299, 0.8018, 0.1547],
        [0.6201, 0.0115, 0.1379, 0.2340]])

In [45]:
# Get  attributes from tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.3111, 0.7698, 0.9164, 0.4658],
        [0.2432, 0.7299, 0.8018, 0.1547],
        [0.6201, 0.0115, 0.1379, 0.2340]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [47]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [52]:
# Multiply tensor by 10 (element-wise)
tensor = torch.tensor([1,2,3])
tensor * 10

tensor([10, 20, 30])

In [49]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [51]:
# PyTorch has built-in functions
print(torch.mul(tensor, 10))
print(torch.add(tensor, 10))
print(torch.subtract(tensor, 10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])


### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise operation (scalar multiplication)
2. Matrix multiplication

In [54]:
# Element-wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [55]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)