# 00. PyTorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors in PyTorch

### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(3)
scalar

tensor(3)

In [6]:
type(scalar)

torch.Tensor

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as Python int
# Converts element to scalar. Cannot be used on higher ndmim objects
scalar.item()

3

In [12]:
# Vector
vector = torch.tensor([1,2])
vector

tensor([1, 2])

In [14]:
# Number of dimension (ndim) corresponds to number of square brackets
vector.ndim

1

In [22]:
# Slicing
vector[0:2]

tensor([1, 2])

In [27]:
# Matrix
# For simplicity use numpy to create a 3x3 array for torch.tensor to use
arr = np.arange(0,9).reshape(3,3)
matrix = torch.tensor(arr)
matrix

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [28]:
matrix.ndim

2

In [29]:
matrix[1]

tensor([3, 4, 5])

In [30]:
matrix[0:2]

tensor([[0, 1, 2],
        [3, 4, 5]])

In [31]:
matrix.shape

torch.Size([3, 3])

In [35]:
# Tensor
arr2 = np.arange(0,18).reshape(2,3,3)
tensor = torch.tensor(arr2)
tensor

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]])

In [36]:
tensor.shape

torch.Size([2, 3, 3])

In [37]:
tensor.ndim

3